version: '3'
services:
  api:
    build: .
    volumes:
      - ./:/usr/src/application:ro
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8000:8000
    environment:
      - POSTGRES_PASSWORD = 12345_12345
      - USER_NAME = postgres
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    ports:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=12345_12345
      - POSTGRES_USER=postgres
      - POSTGRES_DB=weather_db

volumes:
  postgres_data:
